# Dotfiles Configuration
# =======================

# Basic information
name: "dotfiles"
description: "Personalized development environment with ZSH, Oh My Zsh, and useful aliases"
version: "2.0.0"

# Symlinks to create
# Format: target: source (relative to dotfiles directory)
symlinks:
  ~/.zshrc: .zshrc
  ~/.aliases.sh: scripts/.aliases.sh
  ~/.aliases-git.sh: scripts/.aliases-git.sh
  # Optional symlinks (only created if source exists)
  ~/.color-tab.iterm.sh: scripts/.color-tab.iterm.sh
  ~/.completion-git.sh: scripts/.completion-git.sh
  
  # Emacs configuration
  ~/.config/emacs/init.el: .config/emacs/init.el
  ~/.config/emacs/early-init.el: .config/emacs/early-init.el
  ~/.config/emacs/config.org: .config/emacs/config.org
  ~/.config/emacs/themes/zenburn-theme.el: .config/emacs/themes/zenburn-theme.el

# ZSH plugins to install
zsh_plugins:
  - name: zsh-autosuggestions
    url: https://github.com/zsh-users/zsh-autosuggestions
    description: "Fish-like autosuggestions for zsh"
  
  - name: zsh-syntax-highlighting
    url: https://github.com/zsh-users/zsh-syntax-highlighting.git
    description: "Fish shell like syntax highlighting for Zsh"
  
  - name: zsh-completions
    url: https://github.com/zsh-users/zsh-completions
    description: "Additional completion definitions for Zsh"
  
  - name: zsh-docker-aliases
    url: https://github.com/akarzim/zsh-docker-aliases.git
    description: "A bunch of useful Docker aliases for Zsh"

# System packages
packages:
  # Common packages for all systems
  common:
    - git
    - curl
    - wget
    - htop
    - tree
    - fzf
    - bat
    - exa
  
  # Mac-specific packages (via Homebrew)
  mac:
    homebrew_taps:
      - homebrew/cask-fonts
    
    homebrew_packages:
      - git
      - htop
      - fastfetch
      - rsync
      - telnet
      - nmap
      - tree
      - fzf
      - bat
      - exa
      - fd
    
    homebrew_casks: []
  
  # Linux-specific packages (via apt)
  linux:
    apt_packages:
      - git
      - zsh
      - curl
      - wget
      - htop
      - tree
      - emacs
      - docker.io
      - docker-compose

# Backup configuration
backup:
  # Files to backup before installation
  files:
    - ~/.zshrc
    - ~/.aliases.sh
    - ~/.aliases-git.sh
    - ~/.color-tab.iterm.sh
    - ~/.completion-git.sh
    - ~/.gitconfig
    - ~/.vimrc
    - ~/.tmux.conf
    # Emacs configuration
    - ~/.config/emacs/init.el
    - ~/.config/emacs/early-init.el
    - ~/.config/emacs/config.org
    - ~/.config/emacs/themes/zenburn-theme.el
  
  # Backup directory pattern (supports date formatting)
  directory_pattern: "~/.dotfiles-backup-%Y%m%d-%H%M%S"

# Installation options
options:
  # Whether to set ZSH as default shell
  set_default_shell: true
  
  # Whether to install Oh My Zsh
  install_oh_my_zsh: true
  
  # Whether to install system packages
  install_packages: true
  
  # Whether to create backups
  create_backup: true
  
  # Whether to verify installation
  verify_installation: true

# Verification checks
verification:
  # Check these symlinks exist and point to correct targets
  required_symlinks:
    - ~/.zshrc
    - ~/.aliases.sh
    - ~/.aliases-git.sh
    - ~/.config/emacs/init.el
    - ~/.config/emacs/early-init.el
    - ~/.config/emacs/config.org
  
  # Check these ZSH plugins are installed
  required_plugins:
    - zsh-autosuggestions
    - zsh-syntax-highlighting
  
  # Check these commands are available
  required_commands:
    - zsh
    - git
    - curl 